station_conf = {
    'network_name' : "ABC",
    'catalog_path' : "catalog/abc_catalog.bin",
    'content_dir' : "catalog/abc_catalog",
    'runtime_dir' : "runtime/abc",
    'schedule_path': "runtime/abc_schedule.bin",
    #must be inside or linked inside content_dir
    'commercial_dir' : "commercial",
    'bump_dir' : "bump",
    'clip_shows' : ["am_band_stand", "sh_rock"],
    'off_air_image': "runtime/nbc_offair.png",

    #used at sign-off time (played once)
    'sign_off_video': "catalog/anthem_signoff.mp4",
    #used when the channel is offair
    'off_air_video': "catalog/off_air_pattern.mp4",

    'monday': {
        '7': {'tags': 'morning'},
        '8': {'tags': 'morning'},
        '9': {'tags': 'classic'},
        '10': {'tags' : 'saturday_night'},
        '11': {'tags' : 'gameshow'},
        '12': {'tags' : 'daytime'},
        '13': {'tags' : 'daytime'},
        '14': {'tags' : 'daytime'},
        '15': {'tags' : 'daytime'},
        '16': {'tags' : 'syndication'},
        '17': {'tags' : 'syndication'},
        '18': {'tags' : 'news'},
        '19': {'tags' : 'gameshow'},
        '20': {'tags' : 'sitcom'},
        '21': {'tags' : 'prime'},
        '22': {'tags' : 'prime'},
        '23': {'tags' : 'news'},
        '0': {'tags' : 'western'},
        '1': {'tags' : 'classic'},
        '2': {'event' : 'signoff'}
    },
    'tuesday': {
        '7': {'tags': 'morning'},
        '8': {'tags': 'morning'},
        '9': {'tags': 'classic'},
        '10': {'tags' : 'saturday_night'},
        '11': {'tags' : 'gameshow'},
        '12': {'tags' : 'daytime'},
        '13': {'tags' : 'daytime'},
        '14': {'tags' : 'daytime'},
        '15': {'tags' : 'daytime'},
        '16': {'tags' : 'syndication'},
        '17': {'tags' : 'syndication'},
        '18': {'tags' : 'news'},
        '19': {'tags' : 'gameshow'},
        '20': {'tags' : 'sitcom'},
        '21': {'tags' : 'prime'},
        '22': {'tags' : 'prime'},
        '23': {'tags' : 'news'},
        '0': {'tags' : 'western'},
        '1': {'tags' : 'classic'},
        '2': {'event' : 'signoff'}
    },
    'wednesday': {
        '7': {'tags': 'morning'},
        '8': {'tags': 'morning'},
        '9': {'tags': 'classic'},
        '10': {'tags' : 'saturday_night'},
        '11': {'tags' : 'gameshow'},
        '12': {'tags' : 'daytime'},
        '13': {'tags' : 'daytime'},
        '14': {'tags' : 'daytime'},
        '15': {'tags' : 'daytime'},
        '16': {'tags' : 'syndication'},
        '17': {'tags' : 'syndication'},
        '18': {'tags' : 'news'},
        '19': {'tags' : 'gameshow'},
        '20': {'tags' : 'sitcom'},
        '21': {'tags' : 'prime'},
        '22': {'tags' : 'prime'},
        '23': {'tags' : 'news'},
        '0': {'tags' : 'western'},
        '1': {'tags' : 'classic'},
        '2': {'event' : 'signoff'}
    },
    'thursday': {
        '7': {'tags': 'morning'},
        '8': {'tags': 'morning'},
        '9': {'tags': 'classic'},
        '10': {'tags' : 'saturday_night'},
        '11': {'tags' : 'gameshow'},
        '12': {'tags' : 'daytime'},
        '13': {'tags' : 'daytime'},
        '14': {'tags' : 'daytime'},
        '15': {'tags' : 'daytime'},
        '16': {'tags' : 'syndication'},
        '17': {'tags' : 'syndication'},
        '18': {'tags' : 'news'},
        '19': {'tags' : 'gameshow'},
        '20': {'tags' : 'sitcom'},
        '21': {'tags' : 'prime'},
        '22': {'tags' : 'prime'},
        '23': {'tags' : 'news'},
        '0': {'tags' : 'western'},
        '1': {'tags' : 'classic'},
        '2': {'event' : 'signoff'}
    },
    'friday': {
        '7': {'tags': 'morning'},
        '8': {'tags': 'morning'},
        '9': {'tags': 'classic'},
        '10': {'tags' : 'saturday_night'},
        '11': {'tags' : 'gameshow'},
        '12': {'tags' : 'daytime'},
        '13': {'tags' : 'daytime'},
        '14': {'tags' : 'daytime'},
        '15': {'tags' : 'daytime'},
        '16': {'tags' : 'syndication'},
        '17': {'tags' : 'syndication'},
        '18': {'tags' : 'news'},
        '19': {'tags' : 'gameshow'},
        '20': {'tags' : 'sitcom'},
        '21': {'tags' : 'prime'},
        '22': {'tags' : 'prime'},
        '23': {'tags' : 'news'},
        '0': {'tags' : 'western'},
        '1': {'tags' : 'classic'},
        '2': {'event' : 'signoff'}
    },
    'saturday': {
        '7': {'tags': 'cartoon'},
        '8': {'tags': 'cartoon'},
        '9': {'tags': 'cartoon'},
        '10': {'tags' : 'cartoon'},
        '11': {'tags' : 'cartoon'},
        '12': {'tags' : 'cartoon'},
        '13': {'tags' : 'cartoon'},
        '14': {'tags' : 'saturday'},
        '15': {'tags' : 'sports'},
        '16': {'tags' : 'sports'},
        '17': {'tags' : 'sports'},
        '18': {'tags' : 'news'},
        '19': {'tags' : 'syndication'},
        '20': {'tags' : 'sitcom'},
        '21': {'tags' : 'sitcom'},
        '22': {'tags' : 'prime'},
        '23': {'tags' : 'news'},
        '1': {'tags' : 'western'},
        '2': {'event' : 'signoff'}
    },
    'sunday': {
        '7': {'tags': 'cartoon'},
        '8': {'tags': 'cartoon'},
        '9': {'tags': 'classic'},
        '10': {'tags' : 'sunday'},
        '11': {'tags' : 'sunday'},
        '12': {'tags' : 'sunday'},
        '13': {'tags' : 'sports'},
        '14': {'tags' : 'sports'},
        '15': {'tags' : 'sports'},
        '16': {'tags' : 'sports'},
        '17': {'tags' : 'syndication'},
        '18': {'tags' : 'news'},
        '19': {'tags' : 'gameshow'},
        '20': {'tags' : 'sitcom'},
        '21': {'tags' : 'sitcom'},
        '22': {'tags' : 'prime'},
        '23': {'tags' : 'prime'},
        '1': {'tags' : 'classic'},
        '2': {'event' : 'signoff'}
    }
}
