nbc_conf = {
    'network_name' : "NBC",
    'catalog_path' : "nbc_catalog.bin",
    'content_dir' : "shows",
    'runtime_dir' : "runtime/nbc",
    'schedule_path': "runtime/nbc_schedule.bin",
    #must be inside or linked inside content_dir
    'commercial_dir' : "commercial",
    'bump_dir' : "bump",
    'clip_shows' : ["real_people"],
    'off_air_image': "runtime/nbc_offair.png",
    'monday': {
        7: {'tags': 'morning'},
        8: {'tags': 'morning'},
        9: {'tags': 'cartoon'},
        10: {'tags' : 'gameshow'},
        11: {'tags' : 'gameshow'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'classic'},
        16: {'tags' : 'syndication'},
        17: {'tags' : 'syndication'},
        18: {'tags' : 'news'},
        19: {'tags' : 'gameshow'},
        20: {'tags' : 'sitcom'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'late'},
        0: {'tags' : 'late-late'},
        1: {'tags' : 'classic'}
    },
    'tuesday': {
        7: {'tags': 'morning'},
        8: {'tags': 'morning'},
        9: {'tags': 'cartoon'},
        10: {'tags' : 'gameshow'},
        11: {'tags' : 'gameshow'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'classic'},
        16: {'tags' : 'syndication'},
        17: {'tags' : 'syndication'},
        18: {'tags' : 'news'},
        19: {'tags' : 'gameshow'},
        20: {'tags' : 'sitcom'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'late'},
        1: {'tags' : 'late-late'},
        2: {'tags' : 'classic'}
    },
    'wednesday': {
        7: {'tags': 'morning'},
        8: {'tags': 'morning'},
        9: {'tags': 'cartoon'},
        10: {'tags' : 'gameshow'},
        11: {'tags' : 'gameshow'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'classic'},
        16: {'tags' : 'syndication'},
        17: {'tags' : 'syndication'},
        18: {'tags' : 'news'},
        19: {'tags' : 'gameshow'},
        20: {'tags' : 'real_people'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'late'},
        1: {'tags' : 'late-late'},
        2: {'tags' : 'classic'}
    },
    'thursday': {
        7: {'tags': 'morning'},
        8: {'tags': 'morning'},
        9: {'tags': 'cartoon'},
        10: {'tags' : 'gameshow'},
        11: {'tags' : 'gameshow'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'classic'},
        16: {'tags' : 'syndication'},
        17: {'tags' : 'syndication'},
        18: {'tags' : 'news'},
        19: {'tags' : 'gameshow'},
        20: {'tags' : 'sitcom'},
        21: {'tags' : 'sitcom'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'late'},
        1: {'tags' : 'late-late'},
        2: {'tags' : 'classic'}
    },
    'friday': {
        7: {'tags': 'morning'},
        8: {'tags': 'morning'},
        9: {'tags': 'cartoon'},
        10: {'tags' : 'gameshow'},
        11: {'tags' : 'gameshow'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'classic'},
        16: {'tags' : 'syndication'},
        17: {'tags' : 'syndication'},
        18: {'tags' : 'news'},
        19: {'tags' : 'gameshow'},
        20: {'tags' : 'sitcom'},
        21: {'tags' : 'sitcom'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'late'},
        1: {'tags' : 'late-late'},
        2: {'tags' : 'classic'}
    },
    'saturday': {
        7: {'tags': 'cartoon'},
        8: {'tags': 'cartoon'},
        9: {'tags': 'cartoon'},
        10: {'tags' : 'cartoon'},
        11: {'tags' : 'cartoon'},
        12: {'tags' : 'cartoon'},
        13: {'tags' : 'wrestling'},
        14: {'tags' : 'wrestling'},
        15: {'tags' : 'classic'},
        16: {'tags' : 'syndication'},
        17: {'tags' : 'syndication'},
        18: {'tags' : 'news'},
        19: {'tags' : 'gameshow'},
        20: {'tags' : 'sitcom'},
        21: {'tags' : 'sitcom'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'late'},
        1: {'tags' : 'late-late'},
        2: {'tags' : 'classic'}
    },
    'sunday': {
        7: {'tags': 'cartoon'},
        8: {'tags': 'cartoon'},
        9: {'tags': 'classic'},
        10: {'tags' : 'sunday'},
        11: {'tags' : 'sunday'},
        12: {'tags' : 'sunday'},
        13: {'tags' : 'western'},
        14: {'tags' : 'western'},
        15: {'tags' : 'western'},
        16: {'tags' : 'wrestling'},
        17: {'tags' : 'syndication'},
        18: {'tags' : 'news'},
        19: {'tags' : 'gameshow'},
        20: {'tags' : 'sitcom'},
        21: {'tags' : 'real_people'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'prime'},
        24: {'tags' : 'classic'},
        1: {'tags' : 'classic'},
        2: {'tags' : 'classic'}
    }
}
