station_conf = {
    'network_name' : "PBS",
    'catalog_path' : "catalog/pbs_catalog.bin",
    'content_dir' : "catalog/pbs_catalog",
    'runtime_dir' : "runtime/pbs",
    'schedule_path': "runtime/pbs_schedule.bin",
    #must be inside or linked inside content_dir
    'commercial_dir' : "commercial",
    'bump_dir' : "bump",
    'clip_shows' : [],
    'off_air_image': "runtime/nbc_offair.png",
    'monday': {
        7: {'tags': 'kids'},
        8: {'tags': 'kids'},
        9: {'tags': 'kids'},
        10: {'tags' : 'kids'},
        11: {'tags' : 'daytime'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'daytime'},
        16: {'tags' : 'daytime'},
        17: {'tags' : 'daytime'},
        18: {'tags' : 'news'},
        19: {'tags' : 'prime'},
        20: {'tags' : 'prime'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'prime'},
        0: {'tags' : 'prime'},
        1: {'tags' : 'daytime'}
    },
    'tuesday': {
        7: {'tags': 'kids'},
        8: {'tags': 'kids'},
        9: {'tags': 'kids'},
        10: {'tags' : 'kids'},
        11: {'tags' : 'daytime'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'daytime'},
        16: {'tags' : 'daytime'},
        17: {'tags' : 'daytime'},
        18: {'tags' : 'news'},
        19: {'tags' : 'prime'},
        20: {'tags' : 'prime'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'prime'},
        0: {'tags' : 'prime'},
        1: {'tags' : 'daytime'}
    },
    'wednesday': {
        7: {'tags': 'kids'},
        8: {'tags': 'kids'},
        9: {'tags': 'kids'},
        10: {'tags' : 'kids'},
        11: {'tags' : 'daytime'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'daytime'},
        16: {'tags' : 'daytime'},
        17: {'tags' : 'daytime'},
        18: {'tags' : 'news'},
        19: {'tags' : 'prime'},
        20: {'tags' : 'prime'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'prime'},
        0: {'tags' : 'prime'},
        1: {'tags' : 'daytime'}
    },
    'thursday': {
        7: {'tags': 'kids'},
        8: {'tags': 'kids'},
        9: {'tags': 'kids'},
        10: {'tags' : 'kids'},
        11: {'tags' : 'daytime'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'daytime'},
        16: {'tags' : 'daytime'},
        17: {'tags' : 'daytime'},
        18: {'tags' : 'news'},
        19: {'tags' : 'prime'},
        20: {'tags' : 'prime'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'prime'},
        0: {'tags' : 'prime'},
        1: {'tags' : 'daytime'}
    },
    'friday': {
        7: {'tags': 'kids'},
        8: {'tags': 'kids'},
        9: {'tags': 'kids'},
        10: {'tags' : 'kids'},
        11: {'tags' : 'daytime'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'daytime'},
        16: {'tags' : 'daytime'},
        17: {'tags' : 'daytime'},
        18: {'tags' : 'news'},
        19: {'tags' : 'prime'},
        20: {'tags' : 'prime'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'prime'},
        0: {'tags' : 'prime'},
        1: {'tags' : 'daytime'}
    },
    'saturday': {
        7: {'tags': 'kids'},
        8: {'tags': 'kids'},
        9: {'tags': 'kids'},
        10: {'tags' : 'kids'},
        11: {'tags' : 'daytime'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'daytime'},
        16: {'tags' : 'daytime'},
        17: {'tags' : 'daytime'},
        18: {'tags' : 'news'},
        19: {'tags' : 'prime'},
        20: {'tags' : 'prime'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'prime'},
        0: {'tags' : 'prime'},
        1: {'tags' : 'daytime'}
    },
    'sunday': {
        7: {'tags': 'kids'},
        8: {'tags': 'kids'},
        9: {'tags': 'kids'},
        10: {'tags' : 'kids'},
        11: {'tags' : 'daytime'},
        12: {'tags' : 'daytime'},
        13: {'tags' : 'daytime'},
        14: {'tags' : 'daytime'},
        15: {'tags' : 'daytime'},
        16: {'tags' : 'daytime'},
        17: {'tags' : 'daytime'},
        18: {'tags' : 'news'},
        19: {'tags' : 'prime'},
        20: {'tags' : 'prime'},
        21: {'tags' : 'prime'},
        22: {'tags' : 'prime'},
        23: {'tags' : 'news'},
        24: {'tags' : 'prime'},
        0: {'tags' : 'prime'},
        1: {'tags' : 'daytime'}
    }
}
