services:
  fieldstation:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fieldstation42
    volumes:
      # Needed for the app - mounts so data persists
      - ./catalog:/app/catalog
      - ./runtime:/app/runtime
      - ./confs:/app/confs

      # Video (X11 GUI display)
      - /tmp/.X11-unix:/tmp/.X11-unix

      # Audio
      - ${PULSE_SOCKET}:/tmp/pulse-socket

      # Needed to keep time accurate
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

      # If you're using symlinks, mount the directory they point to like so:
      # - /mnt/d/Media/TV:/mnt/d/Media/TV
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/tmp/pulse-socket
      - XDG_RUNTIME_DIR=/tmp
    stdin_open: true
    tty: true
